version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - javac src\main\webapp\WEB-INF\classes\Model\UserBase.java
      - javac src\main\webapp\WEB-INF\classes\Model\DataConnector.java
      - mvn package
      - mv target/ROOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*